# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval_updates: 10000
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  save_dir: /home1/Sathvik/fairseq_models/librilight_checkpoints/ssl
  checkpoint_suffix: _10h_default_ssl_ft
  restore_file: /home1/Sathvik/fairseq_models/wav2vec2/wav2vec_small.pt
  reset_optimizer: true

task:
  _name: audio_pretraining
  data: /home1/Sathvik/fairseq_datasets/LibriLight/fairseq_files/10hr/
  max_sample_size: 250000
  min_sample_size: 32000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: 1400000
  skip_invalid_size_inputs_valid_test: true
  valid_subset: dev_other

distributed_training:
  distributed_world_size: 2
  ddp_backend: legacy_ddp

criterion:
  _name: wav2vec
  infonce: true
  log_keys: ["prob_perplexity","code_perplexity","temp"]
  loss_weights: [0.1, 10]
  

optimization:
  max_update: 40000
  lr: [0.0005]
  update_freq: [8]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01
  

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 2000

model:
  _name: wav2vec2
  quantize_targets: true
  final_dim: 256
  encoder_layerdrop: 0.05
  dropout_input: 0.1
  dropout_features: 0.1
  feature_grad_mult: 0.1
  encoder_embed_dim: 768
